### ISSUE TITLE
Update binary check to avoid warnings

### ISSUE THREAD

**Issue by oschwery** [MichelleKendall/phyloTop#4]
Hi, 

in `phyloCheck.R` on line Line 25 `if(!is.binary.tree(tree)||!is.rooted(tree)) {` could you exchange `is.binary.tree` with `is.binary`?

Apparently APE is deprecating the old version of that function and is now throwing a warning whenever the old version is used.

Thanks!

**Comment by MichelleKendall** [comment]
Thanks ever so much for bringing this to my attention and in such a clear way. I believe it's now fixed as of commit b68d6ab . Any problems let me know, and if not I'll submit an update to CRAN later in the week.

Thanks!

**Comment by oschwery** [comment]
Awesome, thanks for the quick fix! I'll be looking out for the CRAN update too then.

**Comment by oschwery** [comment]
Oh, I just realised I never actually confirmed it works:
I re-ran it and with the github version the errors introduced by the old `is.binary.tree` have now disappeared.
I think the fix isn't on the latest CRAN install though.
Thanks!

**Comment by oschwery** [comment]
Hi @MichelleKendall ,

quick question: were you still going to update this (or the package in general) on CRAN?
If not, I would have to make sure users for my package use the GitHub version, where this is fixed. Shouldn't be a big deal, but I just wanted to check before doing so.

Cheers!
Orlando

**Comment by MichelleKendall** [comment]
Hi,

Wow I'm so sorry this slipped through the net. I came up against the slightest of barriers re needing to change my email address with CRAN, and apparently that was enough to derail the task! I will send an update to CRAN now and confirm here when it's live. Thanks for the prod!

Michelle

**Comment by MichelleKendall** [comment]
Version 2.1.2 is making its way onto CRAN now and should match commit [3751005](https://github.com/MichelleKendall/phyloTop/tree/375100502e08bd20b1f7e7b9d5122615a61dd155), and hopefully doesn't throw any unwelcome warnings. Thanks for bearing with me, and apologies again for the inconvenience in the meantime. 
Best wishes,
Michelle

**Comment by oschwery** [comment]
Awesome, thanks a lot. Ha, no worries, I am pretty sure everyone who maintains a package has been derailed by something like that. We all got other and perhaps more urgent work besides this too... I'll be looking out for the new version to appear on CRAN.
